version: '3'
services:

    web:
        container_name: mw_web
        restart: always
        build: ./
        # During development we map local files into the container
        volumes:
            # Map current working copy into the container
            - ./:/var/www/html/

            # Uncomment to use dev specific PHP settings
            #- ./config/php/local.ini:/etc/php7/conf.d/99-local.ini

            # Uncomment to use the local vendor directory, e.g. for debugging.
            # This requires that you have copied the directory to your host with
            #   docker-compose run --rm web cp -ra /var/www/vendor .
            #- ./vendor:/var/www/vendor
        links:
            - db
        environment:
            # Make sure to tweak this in production
            PHP_FPM_MAX_CHILDREN: 10
            # Enable periodic jobs (see config/crontabs)
            ENABLE_CROND: 1
        ports:
            - "80:80"

    db:
        image: mysql
        container_name: mw_db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - mysql-data-mw:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: miniwallet
            MYSQL_USER: miniwallet
            MYSQL_PASSWORD: password
        ports:
            - "3308:3306"

volumes:
    mysql-data-mw:
        external: true